services:
  mysql:
    extends:
      file: compose.yaml
      service: mysql

  redis:
    extends:
      file: compose.yaml
      service: redis

  mainland:
    extends:
      file: compose.yaml
      service: mainland
    build:
      target: development
    develop:
      watch:
        - action: sync+restart
          path: ./backend/Mainland
          target: /home/Mainland
          initial_sync: true
          ignore:
            - "*/__pycache__/*"

  mainland-celery:
    extends:
      file: compose.yaml
      service: mainland-celery
    build:
      target: development
    develop:
      watch:
        - action: sync+restart
          path: ./backend/Mainland
          target: /home/Mainland
          initial_sync: true
          ignore:
            - "*/__pycache__/*"

  nginx:
    extends:
      file: compose.yaml
      service: nginx
    ports:
      - "${HOST_HTTP_PORT}:80"
