# Generated by Django 6.0.2 on 2026-07-16 20:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='CAS Path')),
                ('ref_count', models.PositiveIntegerField(default=0, verbose_name='Reference Count')),
            ],
            options={
                'verbose_name': 'CAS File',
                'verbose_name_plural': 'CAS Files',
            },
        ),
        migrations.CreateModel(
            name='FileRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('allowed_content_types', models.JSONField(blank=True, default=list, help_text='MIME types allowed for this role, e.g. ["image/jpeg"]. Empty = allow all.')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='File extensions allowed for this role, e.g. [".jpg"]. Empty = allow all.')),
                ('max_count', models.PositiveIntegerField(blank=True, default=None, help_text='Max files with this role per entity (order/product). Null = unlimited.', null=True)),
            ],
            options={
                'verbose_name': 'File Role',
                'verbose_name_plural': 'File Roles',
                'ordering': ['slug'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileRoleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='FileManager.filerole')),
            ],
            options={
                'verbose_name': 'File Role Translation',
                'db_table': 'FileManager_filerole_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='FileManager_filerole_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
