# Generated by Django 6.0.2 on 2026-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casfile',
            name='path',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='CAS Path'),
        ),
    ]
