# Generated by Django 6.0.1 on 2026-08-28 14:57

import django.db.models.deletion
import parler.fields
import parler.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import connection, migrations, models

# Case-insensitive uniqueness on auth.User.email -- a DB-only index, no
# state_operations, since auth.User isn't a model this app owns. NULLIF(UPPER(
# email), '') so a unique index never conflicts on NULL: every blank-email User
# (many across the test suite) stays exempt without a partial index, which MySQL
# doesn't support. MySQL's functional key parts need the extra parens; SQLite
# doesn't. RunSQL (not RunPython + schema_editor.execute) with the vendor branch
# at load time -- RunPython wraps its callable in an atomic savepoint and
# MySQL/InnoDB can't roll back DDL in a transaction (see backend/docs/gotchas.md).
_EMAIL_CI_INDEX = 'auth_user_email_ci_unique'

if connection.vendor == 'sqlite':
    _EMAIL_CI_CREATE = f"CREATE UNIQUE INDEX {_EMAIL_CI_INDEX} ON auth_user (NULLIF(UPPER(email), ''))"
    _EMAIL_CI_DROP = f"DROP INDEX {_EMAIL_CI_INDEX}"
elif connection.vendor == 'mysql':
    _EMAIL_CI_CREATE = f"CREATE UNIQUE INDEX {_EMAIL_CI_INDEX} ON auth_user ((NULLIF(UPPER(email), '')))"
    _EMAIL_CI_DROP = f"DROP INDEX {_EMAIL_CI_INDEX} ON auth_user"
else:
    raise NotImplementedError(f"Unsupported DB vendor for email CI-uniqueness: {connection.vendor}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='role', serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(blank=True, default='', max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='Company.company')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='Profile.role')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': [('view_profile_any_company', 'Can view profiles/users across all companies'), ('delete_profile_any_company', 'Can remove/deactivate profiles/users across all companies'), ('change_sensitive_profile_data', 'Can change role, company, and identity fields on any profile')],
            },
        ),
        migrations.CreateModel(
            name='RoleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='Profile.role')),
            ],
            options={
                'verbose_name': 'Role Translation',
                'db_table': 'Profile_role_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='Profile_role_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunSQL(sql=_EMAIL_CI_CREATE, reverse_sql=_EMAIL_CI_DROP),
    ]
