# Generated by Django 6.0.1 on 2026-09-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='managed_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this profile has role-scoped access to (e.g. for Profile listing/management). Seeded to {company} once at Profile creation (see seed_managed_companies below); freely editable after that -- there is no ongoing re-pin invariant.', related_name='managed_by_profiles', to='Company.company'),
        ),
    ]
