# Generated by Django 6.0.1 on 2026-09-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_delete_any_company_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('change_profile_role', 'Can change which roles a profile holds'), ('change_profile_company', "Can change a profile's company"), ('reset_profile_password', "Can reset another profile's password")], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='role',
            name='assignable',
            field=models.ManyToManyField(blank=True, help_text="Roles a profile holding this role may grant to another profile via Profile.change_profile_role. Data-driven, set by Profile.management.commands.sync_roles' ASSIGNABLE dict -- not derived from anything else.", to='Profile.role'),
        ),
    ]
