# Generated by Django 6.0.1 on 2026-03-25 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.CharField(blank=True, max_length=16, null=True)),
                ('last_access_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_instance_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('modality', models.CharField(blank=True, max_length=32, null=True)),
                ('body_part', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('sop_instance_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('projection', models.CharField(blank=True, choices=[('frontal', 'Frontal'), ('sagittal', 'Sagittal')], max_length=16, null=True)),
                ('reference_points', models.JSONField(blank=True, default=dict, null=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('cols', models.IntegerField(blank=True, null=True)),
                ('slope', models.FloatField(default=1.0)),
                ('intercept', models.FloatField(default=0.0)),
                ('window_center', models.FloatField(default=0.0)),
                ('window_width', models.FloatField(default=0.0)),
                ('is_signed', models.BooleanField(default=False)),
                ('mm_per_pixel', models.FloatField(default=1.0)),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='private/dicom_files/')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Dicom.series')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_instance_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('study_date', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_access_time', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_address', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='Dicom.patient')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Dicom.study'),
        ),
    ]
