# Generated by Django 6.0.1 on 2026-06-18 16:14

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimage',
            name='dicom_file',
            field=models.FileField(blank=True, null=True, storage=common.storages.PrivateMediaStorage(), upload_to='private/dicom_files/'),
        ),
    ]
