# Generated by Django 6.0.1 on 2026-08-14 01:46

import common.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0003_projection_segmentationstatus_and_more'),
        ('FileManager', '0002_alter_casfile_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomimage',
            name='dicom_file',
        ),
        migrations.RemoveField(
            model_name='dicomimage',
            name='file_hash',
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=common.storages.PrivateMediaStorage(), upload_to='', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('size', models.PositiveIntegerField(verbose_name='Size in bytes')),
                ('hash', models.CharField(db_index=True, max_length=128, verbose_name='Hash (SHA-512)')),
                ('local_path', models.CharField(default='/', max_length=256, verbose_name='Local Path')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cas_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='FileManager.casfile', verbose_name='CAS File record')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xray_file', to='Dicom.dicomimage')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='FileManager.filerole', verbose_name='Role')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_files', to='Dicom.study')),
            ],
            options={
                'verbose_name': 'DICOM File',
                'verbose_name_plural': 'DICOM Files',
                'constraints': [models.UniqueConstraint(fields=('study', 'role'), name='dicom_one_file_per_study_role')],
            },
        ),
    ]
