# Generated by Django 6.0.1 on 2026-08-15 13:41

import common.storages
import django.db.models.deletion
from django.conf import settings
from django.core.files.storage import storages
from django.db import migrations, models


def _delete_old_session_thumbnails(apps, schema_editor):
    """UserRecentStudies.thumbnail's column is dropped below -- the physical
    files it pointed at aren't touched by that (migrations never reach into
    storage), so without this they'd become permanently orphaned bytes in the
    private bucket. Session thumbnails are being replaced by
    DicomThumbnail (CAS-backed, per-DicomImage) in this same migration, so
    there's nothing downstream that still needs these old files."""
    UserRecentStudies = apps.get_model('Dicom', 'UserRecentStudies')
    storage = storages['private']
    names = UserRecentStudies.objects.exclude(thumbnail='').exclude(
        thumbnail__isnull=True
    ).values_list('thumbnail', flat=True)
    for name in names:
        storage.delete(name)


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0010_xray_file_roles_recapped'),
        ('FileManager', '0002_alter_casfile_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_delete_old_session_thumbnails, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userrecentstudies',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='DicomThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=common.storages.PrivateMediaStorage(), upload_to='', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('size', models.PositiveIntegerField(verbose_name='Size in bytes')),
                ('hash', models.CharField(db_index=True, max_length=128, verbose_name='Hash (SHA-512)')),
                ('local_path', models.CharField(default='/', max_length=256, verbose_name='Local Path')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cas_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='FileManager.casfile', verbose_name='CAS File record')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_file', to='Dicom.dicomimage')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='FileManager.filerole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'DICOM Thumbnail',
                'verbose_name_plural': 'DICOM Thumbnails',
            },
        ),
    ]
