# Generated by Django 6.0.1 on 2026-08-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0012_patient_id_series_id_study_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentstudies',
            name='frontal_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userrecentstudies',
            name='side_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
