# Generated by Django 6.0.1 on 2026-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0013_userrecentstudies_frontal_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='segmentation_model_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='segmented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
