# Generated by Django 6.0.1 on 2026-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dicom', '0014_dicomimage_segmentation_model_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': [('access_studies', 'Can access, upload, and manage DICOM studies and segmentation sessions')]},
        ),
    ]
